name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.

version: 11.0.0

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_platform_interface
      ref: spr-googlelocaccuracyfix
  geolocator_android:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_android
      ref: spr-googlelocaccuracyfix
  geolocator_apple:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_apple
      ref: spr-googlelocaccuracyfix
  geolocator_web:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_web
      ref: spr-googlelocaccuracyfix
  geolocator_windows:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_windows
      ref: spr-googlelocaccuracyfix

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.0.0
