name: geolocator_u
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 11.0.0

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android_u
      ios:
        default_package: geolocator_apple_u
      macos:
        default_package: geolocator_apple_u
      web:
        default_package: geolocator_web_u
      windows:
        default_package: geolocator_windows_u

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface_u:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_platform_interface
  geolocator_android_u:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_android
  geolocator_apple_u:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_apple
  geolocator_web_u:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_web
  geolocator_windows_u:
    git:
      url: https://github.com/unexus/flutter-geolocator-un3x.git
      path: geolocator_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.0.0
